"""Curated clinical interaction rules (the safety layer of the hybrid DDI system).

The ML models say *whether* two drugs interact and *what kind* of interaction it
is. These rules encode well-established, clinically important interactions
(standard pharmacology references) and supply the severity grade, the plain-language
explanation, symptoms to watch and the safer alternative shown to the user.

A side of a rule is a set of generic names and/or "class:<drug class>" entries.
Rules are checked in order; the first matching rule wins.
"""
from __future__ import annotations

QT_DRUGS = {"azithromycin", "clarithromycin", "erythromycin", "levofloxacin", "ciprofloxacin", "ofloxacin",
            "citalopram", "escitalopram", "haloperidol", "quetiapine", "amiodarone", "ondansetron",
            "domperidone", "hydroxychloroquine", "fluconazole", "ketoconazole", "amitriptyline"}

RULES = [
    {
        "a": {"class:anticoagulant"}, "b": {"class:anticoagulant"}, "severity": "Critical",
        "mechanism": "Duplicate anticoagulation",
        "description": "{a} and {b} are both anticoagulants. Taking two anticoagulants together greatly increases the risk of major bleeding.",
        "why": "Both medicines block blood clotting through the clotting-factor cascade. Together they remove most of the body's ability to stop bleeding.",
        "symptoms": ["Black or tarry stools", "Blood in urine", "Unusual bruising", "Prolonged nosebleeds"],
        "recommendation": "Use only one anticoagulant. Confirm the intended regimen with the prescriber immediately.",
        "alternative": "Continue a single anticoagulant at the prescribed dose.",
    },
    {
        "a": {"class:anticoagulant"}, "b": {"class:antiplatelet"}, "severity": "Critical",
        "mechanism": "Dual pathway hemostasis blockade (clotting factors + platelets)",
        "description": "Combining {a} with {b} markedly increases the risk of serious internal and gastrointestinal bleeding.",
        "why": "{a} reduces clotting factors made by the liver, while {b} stops platelets from sticking together. With both safety nets switched off, bleeding risk multiplies.",
        "symptoms": ["Black or tarry stools", "Vomiting blood or coffee-ground material", "Unexplained large bruises", "Blood in urine"],
        "recommendation": "Re-evaluate whether both are required. If combined therapy is essential, monitor INR/bleeding closely and add gastric protection (e.g. pantoprazole).",
        "alternative": "Discuss with the cardiologist whether anticoagulation alone is sufficient.",
    },
    {
        "a": {"class:anticoagulant"}, "b": {"class:nsaid"}, "severity": "Critical",
        "mechanism": "Anticoagulation + NSAID gastric mucosal injury and platelet inhibition",
        "description": "{b} with {a} substantially increases the risk of gastrointestinal bleeding.",
        "why": "{b} damages the stomach lining and weakens platelet function, while {a} prevents clots from forming. A small stomach injury can therefore turn into a serious bleed.",
        "symptoms": ["Black or tarry stools", "Stomach pain", "Vomiting blood", "Unusual bruising"],
        "recommendation": "Avoid NSAIDs in patients on anticoagulants. Use paracetamol for pain where possible.",
        "alternative": "Paracetamol (acetaminophen) at the lowest effective dose for pain relief.",
    },
    {
        "a": {"class:anticoagulant"}, "b": {"class:ssri", "class:snri"}, "severity": "High",
        "mechanism": "Serotonin-mediated platelet dysfunction + anticoagulation",
        "description": "{b} increases the bleeding risk of {a}.",
        "why": "Platelets need serotonin to clump together. {b} depletes platelet serotonin, which adds to the anticoagulant effect of {a}.",
        "symptoms": ["Easy bruising", "Nosebleeds", "Black stools"],
        "recommendation": "Monitor for bleeding and INR (for warfarin) after starting or changing the antidepressant.",
        "alternative": "Consider gastroprotection and close bleeding monitoring.",
    },
    {
        "a": {"warfarin"}, "b": {"class:macrolide", "class:fluoroquinolone", "class:azole_antifungal", "metronidazole", "amiodarone"},
        "severity": "High",
        "mechanism": "CYP2C9/CYP3A4 inhibition and gut-flora changes raising warfarin effect",
        "description": "{b} can raise the effect of {a} (higher INR), increasing bleeding risk.",
        "why": "{b} slows the liver enzymes that break down {a} (and some antibiotics reduce vitamin K from gut bacteria), so warfarin builds up in the blood.",
        "symptoms": ["Bleeding gums", "Nosebleeds", "Dark urine or stools", "Unusual bruising"],
        "recommendation": "Check INR within 3-5 days of starting {b} and adjust the warfarin dose if needed.",
        "alternative": "Choose an antimicrobial with less effect on warfarin where clinically appropriate.",
    },
    {
        "a": {"class:anticoagulant"}, "b": {"rifampicin", "carbamazepine", "phenytoin"}, "severity": "High",
        "mechanism": "Enzyme induction (CYP3A4 / CYP2C9 / P-gp) reducing anticoagulant levels",
        "description": "{b} speeds up the breakdown of {a}, which can make it ineffective and allow clots or stroke.",
        "why": "{b} switches on liver enzymes that clear {a} from the body faster, so its blood level drops.",
        "symptoms": ["Leg swelling or pain (DVT)", "Sudden weakness or speech difficulty", "Chest pain or breathlessness"],
        "recommendation": "Avoid the combination or monitor anticoagulation closely (INR for warfarin).",
        "alternative": "Discuss an alternative to {b} with the prescriber.",
    },
    {
        "a": {"warfarin"}, "b": {"paracetamol"}, "severity": "Medium",
        "mechanism": "Paracetamol metabolite interference with vitamin K cycle",
        "description": "Regular use of {b} (more than ~2 g/day for several days) can increase the INR in patients on {a}.",
        "why": "A paracetamol metabolite interferes with the enzymes that recycle vitamin K, adding to warfarin's effect.",
        "symptoms": ["Unusual bruising", "Bleeding gums"],
        "recommendation": "Occasional paracetamol is fine; for regular use, monitor INR.",
        "alternative": "Use the lowest effective paracetamol dose for the shortest time.",
    },
    {
        "a": {"clopidogrel"}, "b": {"omeprazole", "esomeprazole"}, "severity": "High",
        "mechanism": "CYP2C19 inhibition blocks clopidogrel activation",
        "description": "{b} reduces the activation of {a}, lowering its protection against heart attack and stent thrombosis.",
        "why": "{a} is a prodrug that the liver enzyme CYP2C19 must activate. {b} blocks CYP2C19, so less active clopidogrel is produced.",
        "symptoms": ["Chest pain", "Shortness of breath", "Sudden weakness (stroke symptoms)"],
        "recommendation": "Switch {b} to pantoprazole 40 mg, which has minimal effect on CYP2C19.",
        "alternative": "Pantoprazole 40 mg once daily.",
    },
    {
        "a": {"aspirin"}, "b": {"class:nsaid"}, "severity": "High",
        "mechanism": "Additive GI toxicity + competitive COX-1 blockade",
        "description": "{b} with {a} increases stomach bleeding risk and can block the heart-protective antiplatelet effect of low-dose aspirin.",
        "why": "{b} occupies the same COX-1 site on platelets that aspirin needs, and both irritate the stomach lining.",
        "symptoms": ["Stomach pain or heartburn", "Black stools", "Vomiting blood"],
        "recommendation": "Avoid regular NSAID use with aspirin. If needed, take aspirin at least 30 minutes before ibuprofen and add gastric protection.",
        "alternative": "Paracetamol for pain relief.",
    },
    {
        "a": {"class:antiplatelet"}, "b": {"class:antiplatelet"}, "severity": "Medium",
        "mechanism": "Dual antiplatelet therapy (additive platelet inhibition)",
        "description": "{a} and {b} together (dual antiplatelet therapy) increase bleeding risk. This combination is often intentional, e.g. after a coronary stent.",
        "why": "The two drugs block platelets through different pathways (COX-1 and P2Y12), giving stronger protection against clots but more bleeding.",
        "symptoms": ["Easy bruising", "Nosebleeds", "Black stools"],
        "recommendation": "Confirm the intended duration of dual therapy. Use gastric protection with pantoprazole (not omeprazole with clopidogrel).",
        "alternative": "Continue as prescribed with gastroprotection and bleeding monitoring.",
    },
    {
        "a": {"class:antiplatelet"}, "b": {"class:nsaid"}, "severity": "High",
        "mechanism": "Additive platelet inhibition + NSAID gastric injury",
        "description": "{b} with {a} increases the risk of gastrointestinal bleeding.",
        "why": "{b} irritates the stomach lining while {a} stops platelets from sealing small bleeds.",
        "symptoms": ["Stomach pain", "Black stools", "Vomiting blood"],
        "recommendation": "Avoid the NSAID if possible; otherwise add a proton pump inhibitor (pantoprazole).",
        "alternative": "Paracetamol for pain relief.",
    },
    {
        "a": {"class:nsaid"}, "b": {"class:nsaid"}, "severity": "High",
        "mechanism": "Therapeutic duplication - additive COX inhibition",
        "description": "{a} and {b} are both NSAIDs. Combining them increases stomach ulcer, bleeding and kidney injury risk without extra pain relief.",
        "why": "Both drugs block the same COX enzymes, so side effects add up but the pain-relieving effect does not.",
        "symptoms": ["Severe stomach pain", "Black stools", "Reduced urine output", "Ankle swelling"],
        "recommendation": "Use only one NSAID at a time.",
        "alternative": "Keep one NSAID, or use paracetamol instead.",
    },
    {
        "a": {"class:opioid"}, "b": {"class:benzodiazepine", "zolpidem", "pregabalin", "gabapentin"}, "severity": "Critical",
        "mechanism": "Additive CNS and respiratory depression",
        "description": "{a} with {b} can cause profound sedation, slowed breathing, coma or death (FDA boxed warning).",
        "why": "Both medicines slow down the brain's breathing centre; together the effect is much stronger than either alone.",
        "symptoms": ["Extreme drowsiness", "Slow or shallow breathing", "Confusion", "Unresponsiveness"],
        "recommendation": "Avoid the combination. If unavoidable, use the lowest doses and monitor breathing closely.",
        "alternative": "Non-sedating alternatives for sleep/anxiety; non-opioid analgesia.",
    },
    {
        "a": {"tramadol"}, "b": {"class:ssri", "class:snri", "class:tca"}, "severity": "High",
        "mechanism": "Serotonergic synergy + CYP2D6 inhibition",
        "description": "{a} with {b} increases the risk of serotonin syndrome and seizures.",
        "why": "Both drugs raise serotonin in the brain. Some antidepressants also block CYP2D6, changing how tramadol is processed.",
        "symptoms": ["Agitation or confusion", "Fast heartbeat", "Fever and sweating", "Muscle twitching or tremor", "Seizures"],
        "recommendation": "Avoid if possible; otherwise use the lowest tramadol dose and monitor for serotonin toxicity.",
        "alternative": "Paracetamol or a non-serotonergic analgesic.",
    },
    {
        "a": {"class:ssri", "class:snri"}, "b": {"class:ssri", "class:snri", "class:tca"}, "severity": "High",
        "mechanism": "Serotonergic duplication",
        "description": "{a} and {b} both increase serotonin, raising the risk of serotonin syndrome.",
        "why": "Two serotonergic antidepressants together can push serotonin to toxic levels.",
        "symptoms": ["Agitation", "Fever", "Tremor", "Fast heartbeat"],
        "recommendation": "Avoid combining serotonergic antidepressants unless supervised by a specialist.",
        "alternative": "Use a single antidepressant at an optimised dose.",
    },
    {
        "a": {"class:triptan"}, "b": {"class:ssri", "class:snri"}, "severity": "Medium",
        "mechanism": "Serotonergic synergy",
        "description": "{a} with {b} may increase the risk of serotonin syndrome.",
        "why": "Both drugs act on serotonin receptors/levels.",
        "symptoms": ["Agitation", "Tremor", "Fever"],
        "recommendation": "Use with caution and watch for serotonin toxicity symptoms.",
        "alternative": "Continue with monitoring.",
    },
    {
        "a": {"class:ace_inhibitor", "class:arb"}, "b": {"class:potassium_sparing_diuretic", "class:potassium_supplement"},
        "severity": "High",
        "mechanism": "Reduced aldosterone + potassium retention (hyperkalemia)",
        "description": "{a} with {b} can raise blood potassium to dangerous levels (hyperkalemia).",
        "why": "{a} lowers aldosterone, the hormone that makes the kidneys excrete potassium, while {b} adds or retains potassium.",
        "symptoms": ["Muscle weakness", "Irregular or slow heartbeat", "Tingling", "Fatigue"],
        "recommendation": "Check serum potassium and kidney function within 1 week and regularly thereafter.",
        "alternative": "Adjust doses based on potassium levels.",
    },
    {
        "a": {"class:potassium_sparing_diuretic"}, "b": {"class:potassium_supplement"}, "severity": "High",
        "mechanism": "Potassium retention + potassium supplementation",
        "description": "{a} with {b} can cause dangerous hyperkalemia.",
        "why": "{a} stops the kidneys from excreting potassium while {b} adds more.",
        "symptoms": ["Muscle weakness", "Irregular heartbeat"],
        "recommendation": "Avoid potassium supplements unless potassium is measured low.",
        "alternative": "Monitor serum potassium.",
    },
    {
        "a": {"class:ace_inhibitor"}, "b": {"class:arb"}, "severity": "High",
        "mechanism": "Dual RAAS blockade",
        "description": "{a} with {b} (dual RAAS blockade) increases the risk of kidney injury, hyperkalemia and low blood pressure without extra benefit.",
        "why": "Both drugs block the same hormone system (renin-angiotensin), so harms add up.",
        "symptoms": ["Dizziness", "Reduced urine output", "Muscle weakness"],
        "recommendation": "Avoid combining an ACE inhibitor with an ARB.",
        "alternative": "Use a single RAAS blocker; add a calcium channel blocker or diuretic if more BP control is needed.",
    },
    {
        "a": {"class:ace_inhibitor", "class:arb"}, "b": {"class:ace_inhibitor", "class:arb"}, "severity": "High",
        "mechanism": "Therapeutic duplication - RAAS blockade",
        "description": "{a} and {b} act on the same blood-pressure hormone system.",
        "why": "Two drugs of the same class give additive side effects (low BP, high potassium, kidney injury).",
        "symptoms": ["Dizziness", "Fainting", "Muscle weakness"],
        "recommendation": "Use only one drug from this class.",
        "alternative": "Keep a single RAAS blocker.",
    },
    {
        "a": {"lithium carbonate"}, "b": {"class:nsaid", "class:ace_inhibitor", "class:arb", "class:thiazide", "class:loop_diuretic"},
        "severity": "High",
        "mechanism": "Reduced renal lithium clearance",
        "description": "{b} reduces kidney clearance of {a}, which can cause lithium toxicity.",
        "why": "The kidneys handle lithium like sodium; {b} changes sodium handling so lithium is retained.",
        "symptoms": ["Tremor", "Confusion", "Vomiting and diarrhoea", "Unsteady walking"],
        "recommendation": "Monitor lithium levels closely or avoid the combination.",
        "alternative": "Paracetamol instead of NSAIDs for pain.",
    },
    {
        "a": {"class:ace_inhibitor", "class:arb"}, "b": {"class:nsaid"}, "severity": "Medium",
        "mechanism": "Renal prostaglandin inhibition (reduced antihypertensive effect, AKI risk)",
        "description": "{b} can reduce the blood-pressure-lowering effect of {a} and increase the risk of kidney injury.",
        "why": "{b} blocks prostaglandins that keep kidney blood vessels open, while {a} lowers the pressure that drives kidney filtration.",
        "symptoms": ["Reduced urine output", "Swelling of legs", "Raised blood pressure"],
        "recommendation": "Limit NSAID use; monitor blood pressure and kidney function, especially in older patients or with diuretics.",
        "alternative": "Paracetamol for pain.",
    },
    {
        "a": {"digoxin"}, "b": {"class:loop_diuretic", "class:thiazide"}, "severity": "High",
        "mechanism": "Diuretic-induced hypokalemia sensitising the heart to digoxin",
        "description": "{b} can lower potassium and magnesium, which increases the risk of {a} toxicity and arrhythmias.",
        "why": "Digoxin binds the heart's Na+/K+ pump more strongly when potassium is low, so toxicity can occur even at normal digoxin levels.",
        "symptoms": ["Nausea or vomiting", "Irregular heartbeat", "Blurred or yellow vision", "Confusion"],
        "recommendation": "Monitor serum potassium (keep > 4.0 mEq/L), magnesium and digoxin levels.",
        "alternative": "Consider potassium supplementation or a potassium-sparing diuretic.",
    },
    {
        "a": {"digoxin"}, "b": {"amiodarone", "verapamil", "clarithromycin", "erythromycin"}, "severity": "High",
        "mechanism": "P-glycoprotein inhibition raising digoxin levels",
        "description": "{b} raises blood levels of {a}, increasing the risk of digoxin toxicity.",
        "why": "{b} blocks P-glycoprotein, the transporter that removes digoxin through the kidneys and gut.",
        "symptoms": ["Nausea", "Slow or irregular heartbeat", "Visual disturbance"],
        "recommendation": "Reduce the digoxin dose (often by 30-50%) and monitor digoxin levels.",
        "alternative": "Choose an alternative to {b} where possible.",
    },
    {
        "a": {"colchicine"}, "b": {"clarithromycin", "erythromycin", "ketoconazole", "verapamil", "diltiazem"}, "severity": "Critical",
        "mechanism": "CYP3A4 + P-gp inhibition causing colchicine toxicity",
        "description": "{b} can raise {a} to toxic, potentially fatal levels.",
        "why": "{b} blocks both the enzyme and the transporter that clear colchicine.",
        "symptoms": ["Severe diarrhoea", "Muscle pain or weakness", "Low blood counts"],
        "recommendation": "Avoid the combination, or greatly reduce the colchicine dose under specialist advice.",
        "alternative": "Use an alternative antibiotic (e.g. azithromycin).",
    },
    {
        "a": {"simvastatin", "atorvastatin"}, "b": {"clarithromycin", "erythromycin", "ketoconazole", "fluconazole"}, "severity": "High",
        "mechanism": "CYP3A4 inhibition raising statin levels (myopathy / rhabdomyolysis)",
        "description": "{b} raises blood levels of {a}, increasing the risk of muscle damage (rhabdomyolysis).",
        "why": "{a} is cleared by CYP3A4; {b} blocks this enzyme, so the statin builds up in muscle tissue.",
        "symptoms": ["Unexplained muscle pain or weakness", "Dark (cola-coloured) urine"],
        "recommendation": "Pause the statin during the course of {b}, or use a statin not cleared by CYP3A4.",
        "alternative": "Rosuvastatin or pravastatin; or azithromycin as the antibiotic.",
    },
    {
        "a": {"linezolid"}, "b": {"class:ssri", "class:snri", "class:tca", "tramadol"}, "severity": "High",
        "mechanism": "MAO inhibition + serotonin reuptake inhibition (serotonin syndrome)",
        "description": "{a} with {b} can cause serotonin syndrome.",
        "why": "{a} blocks monoamine oxidase, the enzyme that breaks down serotonin, while {b} raises serotonin levels.",
        "symptoms": ["Agitation or confusion", "Fever and sweating", "Muscle twitching", "Fast heartbeat"],
        "recommendation": "Avoid the combination; if linezolid is essential, stop the antidepressant and monitor closely.",
        "alternative": "An antibiotic without MAO-inhibiting activity.",
    },
    {
        "a": {"class:calcineurin_inhibitor"}, "b": {"clarithromycin", "erythromycin", "class:azole_antifungal", "diltiazem", "verapamil"},
        "severity": "High",
        "mechanism": "CYP3A4 inhibition raising immunosuppressant levels",
        "description": "{b} raises the blood level of {a}, which can damage the kidneys and nerves.",
        "why": "{a} is cleared by the liver enzyme CYP3A4, which {b} blocks.",
        "symptoms": ["Reduced urine output", "Tremor", "Headache", "High blood pressure"],
        "recommendation": "Monitor {a} blood levels and kidney function closely; a dose reduction is usually needed.",
        "alternative": "Azithromycin instead of clarithromycin/erythromycin where appropriate.",
    },
    {
        "a": {"allopurinol"}, "b": {"class:thiopurine"}, "severity": "Critical",
        "mechanism": "Xanthine oxidase inhibition blocks thiopurine breakdown",
        "description": "{a} blocks the breakdown of {b}, which can cause severe, life-threatening bone-marrow suppression.",
        "why": "{b} is inactivated by xanthine oxidase - the enzyme that {a} blocks - so toxic levels build up.",
        "symptoms": ["Fever or frequent infections", "Unusual bleeding or bruising", "Extreme tiredness"],
        "recommendation": "Avoid, or reduce the {b} dose to about one quarter with close blood-count monitoring.",
        "alternative": "Febuxostat is not a safe substitute either - discuss with a specialist.",
    },
    {
        "a": {"rifampicin", "carbamazepine", "phenytoin"}, "b": {"class:hormonal_contraceptive"}, "severity": "High",
        "mechanism": "Liver enzyme induction reducing hormone levels",
        "description": "{a} lowers the level of {b}, so the contraceptive may fail.",
        "why": "{a} switches on liver enzymes that break down contraceptive hormones faster.",
        "symptoms": ["Breakthrough bleeding", "Risk of unplanned pregnancy"],
        "recommendation": "Use an additional non-hormonal method (e.g. condoms) during treatment and for 28 days after.",
        "alternative": "Copper IUD or another non-hormonal method.",
    },
    {
        "a": {"ketorolac"}, "b": {"probenecid"}, "severity": "High",
        "mechanism": "Reduced renal clearance of ketorolac",
        "description": "{b} greatly increases the level of {a}; this combination is contraindicated.",
        "why": "{b} blocks the kidney transporters that remove {a}.",
        "symptoms": ["Stomach pain", "Black stools", "Reduced urine output"],
        "recommendation": "Do not combine.",
        "alternative": "Another analgesic such as paracetamol.",
    },
    {
        "a": {"class:pde5_inhibitor"}, "b": {"class:nitrate"}, "severity": "Critical",
        "mechanism": "Additive cGMP-mediated vasodilation",
        "description": "{a} with {b} can cause a sudden, severe drop in blood pressure. This combination is contraindicated.",
        "why": "Both drugs relax blood vessels through the nitric oxide / cGMP pathway.",
        "symptoms": ["Fainting", "Severe dizziness", "Chest pain"],
        "recommendation": "Do not combine. Separate by at least 24 hours.",
        "alternative": "Discuss alternative treatments with the prescriber.",
    },
    {
        "a": {"methotrexate"}, "b": {"class:nsaid"}, "severity": "High",
        "mechanism": "Reduced renal methotrexate clearance",
        "description": "{b} can reduce the kidney clearance of {a}, increasing bone-marrow and kidney toxicity.",
        "why": "NSAIDs reduce kidney blood flow and compete for the same kidney transporters.",
        "symptoms": ["Mouth ulcers", "Fever or infections", "Unusual bleeding"],
        "recommendation": "Avoid with high-dose methotrexate; monitor blood counts and kidney function with low doses.",
        "alternative": "Paracetamol for pain.",
    },
    {
        "a": {"theophylline"}, "b": {"ciprofloxacin", "erythromycin", "clarithromycin"}, "severity": "High",
        "mechanism": "CYP1A2 / CYP3A4 inhibition raising theophylline levels",
        "description": "{b} raises {a} levels, risking seizures and arrhythmias.",
        "why": "{b} blocks the liver enzyme that breaks down theophylline.",
        "symptoms": ["Nausea", "Fast heartbeat", "Tremor", "Seizures"],
        "recommendation": "Monitor theophylline levels or choose another antibiotic.",
        "alternative": "An antibiotic without CYP1A2 inhibition.",
    },
    {
        "a": {"class:beta_blocker"}, "b": {"verapamil", "diltiazem"}, "severity": "High",
        "mechanism": "Additive negative chronotropy / AV-node block",
        "description": "{a} with {b} can cause severe slow heart rate, heart block or heart failure.",
        "why": "Both drugs slow the heart's electrical conduction through the AV node.",
        "symptoms": ["Very slow pulse", "Dizziness or fainting", "Breathlessness"],
        "recommendation": "Avoid or monitor heart rate and ECG closely.",
        "alternative": "Use a dihydropyridine CCB such as amlodipine instead.",
    },
    {
        "a": {"class:sulfonylurea"}, "b": {"fluconazole", "clarithromycin", "ciprofloxacin", "levofloxacin"}, "severity": "Medium",
        "mechanism": "CYP2C9 inhibition / glucose regulation changes",
        "description": "{b} can increase the blood-sugar-lowering effect of {a} (hypoglycemia).",
        "why": "{b} slows the breakdown of {a} or directly affects insulin release.",
        "symptoms": ["Sweating", "Shakiness", "Confusion", "Fast heartbeat"],
        "recommendation": "Monitor blood glucose closely during the course of {b}.",
        "alternative": "Temporary dose reduction of {a} if glucose runs low.",
    },
    {
        "a": {"class:ssri", "class:snri"}, "b": {"class:nsaid", "class:antiplatelet"}, "severity": "Medium",
        "mechanism": "Platelet serotonin depletion + GI injury",
        "description": "{a} with {b} increases the risk of gastrointestinal bleeding.",
        "why": "{a} reduces serotonin inside platelets, weakening clotting, while {b} affects platelets and/or the stomach lining.",
        "symptoms": ["Black stools", "Stomach pain", "Easy bruising"],
        "recommendation": "Consider gastric protection (PPI) and monitor for bleeding.",
        "alternative": "Paracetamol for pain where possible.",
    },
    {
        "a": {"class:benzodiazepine", "zolpidem"}, "b": {"class:benzodiazepine", "zolpidem", "class:antipsychotic"}, "severity": "High",
        "mechanism": "Additive CNS depression",
        "description": "{a} with {b} causes additive sedation and can impair breathing, especially in older adults.",
        "why": "Both medicines depress brain activity.",
        "symptoms": ["Excessive sleepiness", "Confusion", "Falls", "Slow breathing"],
        "recommendation": "Avoid combining sedatives; use the lowest effective doses.",
        "alternative": "Use a single sedative agent.",
    },
    {
        "a": {"class:corticosteroid"}, "b": {"class:nsaid"}, "severity": "Medium",
        "mechanism": "Additive GI mucosal injury",
        "description": "{a} with {b} increases the risk of stomach ulcers and bleeding.",
        "why": "Both drugs reduce the protective prostaglandins in the stomach lining.",
        "symptoms": ["Stomach pain", "Black stools"],
        "recommendation": "Add a proton pump inhibitor if the combination is necessary.",
        "alternative": "Paracetamol for pain.",
    },
    {
        "a": {"class:fluoroquinolone", "class:tetracycline"}, "b": {"calcium carbonate"}, "severity": "Medium",
        "mechanism": "Chelation reducing antibiotic absorption",
        "description": "{b} binds {a} in the gut and reduces its absorption, which can cause treatment failure.",
        "why": "Calcium forms an insoluble complex with the antibiotic.",
        "symptoms": ["Infection not improving"],
        "recommendation": "Take {a} 2 hours before or 6 hours after {b}.",
        "alternative": "Separate the doses in time.",
    },
    {
        "a": {"levothyroxine"}, "b": {"class:ppi", "calcium carbonate"}, "severity": "Low",
        "mechanism": "Reduced levothyroxine absorption",
        "description": "{b} can reduce the absorption of {a}.",
        "why": "Levothyroxine needs stomach acid for absorption and can bind to calcium.",
        "symptoms": ["Tiredness", "Weight gain", "Feeling cold"],
        "recommendation": "Take levothyroxine on an empty stomach, 4 hours apart from calcium; check TSH after starting a PPI.",
        "alternative": "Separate doses in time.",
    },
    {
        "a": {"class:ppi", "class:h2_blocker"}, "b": {"class:ppi", "class:h2_blocker"}, "severity": "Low",
        "mechanism": "Therapeutic duplication - acid suppression",
        "description": "{a} and {b} both reduce stomach acid; using both is usually unnecessary.",
        "why": "They act on the same goal (acid suppression) through the same or overlapping pathways.",
        "symptoms": ["Usually none; long-term: low magnesium or B12"],
        "recommendation": "Use a single acid-suppressing drug unless specifically indicated.",
        "alternative": "Keep one acid-suppressing agent.",
    },
    {
        "a": {"class:statin"}, "b": {"class:statin"}, "severity": "Medium",
        "mechanism": "Therapeutic duplication - HMG-CoA reductase inhibition",
        "description": "{a} and {b} are both statins; together they increase muscle-toxicity risk.",
        "why": "Two statins give additive exposure without added benefit.",
        "symptoms": ["Muscle pain or weakness"],
        "recommendation": "Use a single statin.",
        "alternative": "Adjust the dose of one statin instead.",
    },
    {
        "a": {"class:beta_blocker"}, "b": {"class:beta_blocker"}, "severity": "Medium",
        "mechanism": "Therapeutic duplication - beta blockade",
        "description": "{a} and {b} are both beta blockers.",
        "why": "Two beta blockers cause additive slowing of heart rate and lowering of blood pressure.",
        "symptoms": ["Slow pulse", "Dizziness", "Fatigue"],
        "recommendation": "Use only one beta blocker.",
        "alternative": "Adjust the dose of a single beta blocker.",
    },
    {
        "a": {"class:sulfonylurea"}, "b": {"class:sulfonylurea"}, "severity": "Medium",
        "mechanism": "Therapeutic duplication - insulin secretagogues",
        "description": "{a} and {b} are both sulfonylureas; together they raise hypoglycemia risk.",
        "why": "Both stimulate insulin release from the pancreas.",
        "symptoms": ["Sweating", "Shakiness", "Confusion"],
        "recommendation": "Use only one sulfonylurea.",
        "alternative": "Add a drug from a different class if more control is needed.",
    },
    {
        "a": {"class:antihistamine"}, "b": {"class:antihistamine"}, "severity": "Low",
        "mechanism": "Additive antihistamine / sedative effect",
        "description": "{a} and {b} are both antihistamines and may add to drowsiness.",
        "why": "Both block histamine H1 receptors.",
        "symptoms": ["Drowsiness", "Dry mouth"],
        "recommendation": "Usually one antihistamine is enough; avoid driving if drowsy.",
        "alternative": "Use a single non-sedating antihistamine.",
    },
    {
        "a": {"class:ccb"}, "b": {"class:ace_inhibitor", "class:arb", "class:beta_blocker", "class:thiazide"}, "severity": "Low",
        "mechanism": "Additive blood-pressure lowering (intended combination)",
        "description": "{a} and {b} both lower blood pressure. This is a common, intended combination; the main risk is dizziness from low blood pressure.",
        "why": "The two drugs lower blood pressure through different mechanisms, so their effects add up.",
        "symptoms": ["Dizziness when standing up", "Light-headedness"],
        "recommendation": "Monitor blood pressure; rise slowly from sitting or lying.",
        "alternative": "Continue as prescribed with blood-pressure monitoring.",
    },
]

QT_RULE = {
    "severity": "High",
    "mechanism": "Additive QTc interval prolongation",
    "description": "{a} and {b} can both prolong the QT interval; together they increase the risk of a dangerous heart rhythm (torsades de pointes).",
    "why": "Both drugs slow the heart's electrical recovery (repolarisation) after each beat.",
    "symptoms": ["Palpitations", "Fainting", "Dizziness", "Seizure-like episodes"],
    "recommendation": "Avoid the combination if possible; otherwise obtain an ECG and check potassium and magnesium.",
    "alternative": "Choose an alternative that does not prolong the QT interval.",
}


def _matches(side: set[str], generic: str, drug_class: str | None) -> bool:
    return generic in side or (drug_class is not None and f"class:{drug_class}" in side)


def find_rule(g1: str, c1: str | None, g2: str, c2: str | None) -> dict | None:
    """Return the first curated rule matching the pair, with names ordered as in the rule text."""
    for rule in RULES:
        if _matches(rule["a"], g1, c1) and _matches(rule["b"], g2, c2):
            return {**rule, "first": g1, "second": g2}
        if _matches(rule["a"], g2, c2) and _matches(rule["b"], g1, c1):
            return {**rule, "first": g2, "second": g1}
    if g1 in QT_DRUGS and g2 in QT_DRUGS:
        return {**QT_RULE, "first": g1, "second": g2}
    return None
