"""Hand-curated drug catalog: generic names, pharmacological class and brand names.

build_vocabulary.py enriches this list with the chemical structure from PubChem
and the matching DrugBank ID / SMILES from the DDI training data, and writes
shared/drug_vocabulary.json, which the OCR parser, the Node server and the
Python ML API all use for drug-name normalisation.

Format: generic -> (drug class, [brand names / synonyms], optional PubChem query)
"""

GENERICS = {
    # Analgesics / NSAIDs
    "paracetamol": ("analgesic", ["acetaminophen", "dolo", "crocin", "calpol", "tylenol", "pacimol", "p-650", "febrex"], "acetaminophen"),
    "ibuprofen": ("nsaid", ["brufen", "advil", "motrin", "ibugesic"], None),
    "naproxen": ("nsaid", ["naprosyn", "aleve", "naxdom"], None),
    "diclofenac": ("nsaid", ["voveran", "voltaren", "dynapar"], None),
    "aceclofenac": ("nsaid", ["hifenac", "aceclo"], None),
    "mefenamic acid": ("nsaid", ["meftal", "ponstan"], None),
    "ketorolac": ("nsaid", ["ketorol", "toradol"], None),
    "etoricoxib": ("nsaid", ["etoshine", "arcoxia"], None),
    "celecoxib": ("nsaid", ["celebrex"], None),
    "meloxicam": ("nsaid", ["mobic"], None),
    "indomethacin": ("nsaid", ["indocin", "indocap"], None),
    "aspirin": ("antiplatelet", ["ecosprin", "disprin", "acetylsalicylic acid", "loprin"], None),
    "tramadol": ("opioid", ["ultram", "contramal", "tramazac"], None),
    "codeine": ("opioid", [], None),
    "morphine": ("opioid", [], None),
    "oxycodone": ("opioid", ["oxycontin"], None),
    # Anticoagulants / antiplatelets
    "warfarin": ("anticoagulant", ["coumadin", "warf", "uniwarfin"], None),
    "apixaban": ("anticoagulant", ["eliquis", "apigat"], None),
    "rivaroxaban": ("anticoagulant", ["xarelto"], None),
    "dabigatran": ("anticoagulant", ["pradaxa"], "dabigatran etexilate"),
    "clopidogrel": ("antiplatelet", ["plavix", "clopilet", "clavix", "deplatt"], None),
    "ticagrelor": ("antiplatelet", ["brilinta"], None),
    "prasugrel": ("antiplatelet", ["effient", "prasita"], None),
    # Gastro
    "pantoprazole": ("ppi", ["pantocid", "pan 40", "pan-40", "protonix", "pantop"], None),
    "omeprazole": ("ppi", ["omez", "prilosec", "ocid"], None),
    "esomeprazole": ("ppi", ["nexium", "nexpro", "esoz"], None),
    "rabeprazole": ("ppi", ["razo", "rablet", "aciphex"], None),
    "lansoprazole": ("ppi", ["prevacid", "lanzol"], None),
    "ranitidine": ("h2_blocker", ["rantac", "aciloc", "zinetac", "zantac"], None),
    "famotidine": ("h2_blocker", ["pepcid", "famocid"], None),
    "domperidone": ("antiemetic", ["domstal", "motilium"], None),
    "ondansetron": ("antiemetic", ["emeset", "ondem", "zofran", "vomikind"], None),
    "metoclopramide": ("antiemetic", ["perinorm", "reglan"], None),
    "doxylamine": ("antihistamine", [], None),
    "pyridoxine": ("vitamin", ["vitamin b6"], None),
    "loperamide": ("antidiarrheal", ["imodium", "eldoper"], None),
    # Antibiotics / antimicrobials
    "amoxicillin": ("penicillin", ["mox", "novamox", "amoxil"], None),
    "clavulanic acid": ("beta_lactamase_inhibitor", ["clavulanate"], None),
    "azithromycin": ("macrolide", ["azee", "azithral", "zithromax"], None),
    "clarithromycin": ("macrolide", ["zoclar", "claribid", "biaxin"], None),
    "erythromycin": ("macrolide", ["erythrocin"], None),
    "ciprofloxacin": ("fluoroquinolone", ["ciplox", "cipro", "cifran"], None),
    "levofloxacin": ("fluoroquinolone", ["levaquin", "levoflox", "glevo"], None),
    "ofloxacin": ("fluoroquinolone", ["zanocin", "oflox"], None),
    "doxycycline": ("tetracycline", ["doxy-1", "vibramycin", "doxt"], None),
    "cefixime": ("cephalosporin", ["taxim-o", "zifi", "suprax"], None),
    "cefuroxime": ("cephalosporin", ["ceftum", "zinnat"], None),
    "ceftriaxone": ("cephalosporin", ["monocef", "rocephin"], None),
    "metronidazole": ("nitroimidazole", ["flagyl", "metrogyl"], None),
    "fluconazole": ("azole_antifungal", ["forcan", "diflucan", "zocon"], None),
    "ketoconazole": ("azole_antifungal", ["nizoral"], None),
    "rifampicin": ("antitubercular", ["rifampin", "rcinex"], "rifampin"),
    "linezolid": ("oxazolidinone", ["zyvox", "lizolid", "linospan"], None),
    "cefalexin": ("cephalosporin", ["cephalexin", "phexin", "sporidex", "keflex"], "cephalexin"),
    "probenecid": ("uricosuric", ["benemid"], None),
    "isoniazid": ("antitubercular", [], None),
    "hydroxychloroquine": ("antimalarial", ["hcqs", "plaquenil"], None),
    # Cardiovascular
    "lisinopril": ("ace_inhibitor", ["zestril", "prinivil", "listril"], None),
    "enalapril": ("ace_inhibitor", ["envas", "vasotec"], None),
    "ramipril": ("ace_inhibitor", ["cardace", "altace"], None),
    "losartan": ("arb", ["losar", "cozaar", "repace"], None),
    "telmisartan": ("arb", ["telma", "micardis", "telsartan"], None),
    "valsartan": ("arb", ["diovan", "valent"], None),
    "olmesartan": ("arb", ["olmezest", "benicar"], None),
    "amlodipine": ("ccb", ["amlong", "amlodac", "norvasc", "stamlo"], None),
    "nifedipine": ("ccb", ["adalat", "depin"], None),
    "diltiazem": ("ccb", ["dilzem", "cardizem"], None),
    "verapamil": ("ccb", ["calaptin", "calan"], None),
    "metoprolol": ("beta_blocker", ["metolar", "lopressor", "toprol", "betaloc"], None),
    "atenolol": ("beta_blocker", ["aten", "tenormin"], None),
    "propranolol": ("beta_blocker", ["ciplar", "inderal"], None),
    "carvedilol": ("beta_blocker", ["carca", "coreg"], None),
    "bisoprolol": ("beta_blocker", ["concor"], None),
    "furosemide": ("loop_diuretic", ["lasix", "frusemide"], None),
    "torsemide": ("loop_diuretic", ["dytor", "demadex"], None),
    "hydrochlorothiazide": ("thiazide", ["hctz", "aquazide"], None),
    "spironolactone": ("potassium_sparing_diuretic", ["aldactone"], None),
    "eplerenone": ("potassium_sparing_diuretic", ["inspra", "eptus"], None),
    "digoxin": ("cardiac_glycoside", ["lanoxin"], None),
    "amiodarone": ("antiarrhythmic", ["cordarone", "tachyra"], None),
    "atorvastatin": ("statin", ["lipitor", "atorva", "storvas", "atocor"], None),
    "rosuvastatin": ("statin", ["crestor", "rosuvas", "rozavel"], None),
    "simvastatin": ("statin", ["zocor", "simvotin"], None),
    "isosorbide mononitrate": ("nitrate", ["monotrate", "imdur"], None),
    "sildenafil": ("pde5_inhibitor", ["viagra", "penegra"], None),
    "potassium chloride": ("potassium_supplement", ["kcl", "k-dur", "klor-con"], None),
    "isosorbide dinitrate": ("nitrate", ["isordil", "sorbitrate", "isdn"], None),
    "nitroglycerin": ("nitrate", ["glyceryl trinitrate", "gtn", "nitrostat", "angised"], None),
    "tadalafil": ("pde5_inhibitor", ["cialis", "tadacip"], None),
    # Diabetes / endocrine
    "metformin": ("biguanide", ["glycomet", "glucophage", "obimet"], None),
    "glimepiride": ("sulfonylurea", ["amaryl", "glimy"], None),
    "gliclazide": ("sulfonylurea", ["diamicron", "glizid"], None),
    "glibenclamide": ("sulfonylurea", ["glyburide", "daonil"], "glyburide"),
    "sitagliptin": ("dpp4_inhibitor", ["januvia", "istavel"], None),
    "pioglitazone": ("thiazolidinedione", ["actos", "pioz"], None),
    "levothyroxine": ("thyroid_hormone", ["thyronorm", "eltroxin", "synthroid", "thyrox"], None),
    "ethinylestradiol": ("hormonal_contraceptive", ["ethinyl estradiol", "oral contraceptive pill", "ocp"], "ethinyl estradiol"),
    "levonorgestrel": ("hormonal_contraceptive", ["i-pill", "unwanted 72", "plan b"], None),
    "tacrolimus": ("calcineurin_inhibitor", ["prograf", "pangraf", "tacrograf"], None),
    "cyclosporine": ("calcineurin_inhibitor", ["ciclosporin", "cyclosporin", "neoral", "sandimmune"], None),
    "azathioprine": ("thiopurine", ["imuran", "azoran"], None),
    "mercaptopurine": ("thiopurine", ["purinethol", "6-mp"], None),
    "prednisolone": ("corticosteroid", ["wysolone", "omnacortil"], None),
    "prednisone": ("corticosteroid", [], None),
    "dexamethasone": ("corticosteroid", ["decadron", "dexona"], None),
    # CNS
    "fluoxetine": ("ssri", ["prozac", "fludac"], None),
    "sertraline": ("ssri", ["zoloft", "serta", "daxid"], None),
    "escitalopram": ("ssri", ["nexito", "lexapro", "cipralex"], None),
    "citalopram": ("ssri", ["celexa"], None),
    "paroxetine": ("ssri", ["paxil"], None),
    "amitriptyline": ("tca", ["tryptomer", "elavil"], None),
    "duloxetine": ("snri", ["cymbalta", "duzela"], None),
    "alprazolam": ("benzodiazepine", ["xanax", "alprax", "restyl"], None),
    "clonazepam": ("benzodiazepine", ["klonopin", "rivotril", "clonotril"], None),
    "diazepam": ("benzodiazepine", ["valium", "calmpose"], None),
    "zolpidem": ("hypnotic", ["ambien", "zolfresh"], None),
    "gabapentin": ("anticonvulsant", ["neurontin", "gabapin"], None),
    "pregabalin": ("anticonvulsant", ["lyrica", "pregaba"], None),
    "carbamazepine": ("anticonvulsant", ["tegretol", "zen retard"], None),
    "phenytoin": ("anticonvulsant", ["dilantin", "eptoin"], None),
    "valproic acid": ("anticonvulsant", ["valproate", "divalproex", "valparin", "depakote", "encorate"], None),
    "levetiracetam": ("anticonvulsant", ["keppra", "levipil"], None),
    "lithium carbonate": ("mood_stabilizer", ["lithium", "licab", "lithosun"], None),
    "haloperidol": ("antipsychotic", ["haldol", "serenace"], None),
    "olanzapine": ("antipsychotic", ["zyprexa", "oleanz"], None),
    "quetiapine": ("antipsychotic", ["seroquel", "qutipin"], None),
    "sumatriptan": ("triptan", ["imitrex", "suminat"], None),
    # Respiratory / allergy
    "montelukast": ("leukotriene_antagonist", ["montair", "montek", "singulair"], None),
    "cetirizine": ("antihistamine", ["cetzine", "okacet", "zyrtec", "alerid"], None),
    "levocetirizine": ("antihistamine", ["levocet", "xyzal", "teczine"], None),
    "fexofenadine": ("antihistamine", ["allegra", "fexova"], None),
    "loratadine": ("antihistamine", ["claritin", "lorfast"], None),
    "chlorpheniramine": ("antihistamine", ["piriton", "cpm"], "chlorphenamine"),
    "salbutamol": ("beta2_agonist", ["albuterol", "asthalin", "ventolin"], "albuterol"),
    "theophylline": ("methylxanthine", ["theo-24", "deriphyllin"], None),
    # Urology / gout / misc
    "tamsulosin": ("alpha_blocker", ["urimax", "flomax"], None),
    "allopurinol": ("xanthine_oxidase_inhibitor", ["zyloric", "zyloprim"], None),
    "colchicine": ("antigout", ["zycolchin", "colcrys"], None),
    "methotrexate": ("antimetabolite", ["folitrax", "trexall"], None),
    "isoxsuprine": ("vasodilator", ["gestakind", "duvadilan"], None),
    "folic acid": ("vitamin", ["folvite", "folate"], None),
    "cyanocobalamin": ("vitamin", ["vitamin b12"], None),
    "calcium carbonate": ("mineral_supplement", ["shelcal"], None),
    "vitamin d3": ("vitamin", ["cholecalciferol", "calcirol", "uprise d3"], "cholecalciferol"),
}

# Brand combinations -> ingredients (every ingredient must be a key of GENERICS)
COMBINATIONS = {
    "combiflam": ["ibuprofen", "paracetamol"],
    "ultracet": ["tramadol", "paracetamol"],
    "augmentin": ["amoxicillin", "clavulanic acid"],
    "moxclav": ["amoxicillin", "clavulanic acid"],
    "clavam": ["amoxicillin", "clavulanic acid"],
    "pan d": ["pantoprazole", "domperidone"],
    "pantocid dsr": ["pantoprazole", "domperidone"],
    "rabeprazole domperidone": ["rabeprazole", "domperidone"],
    "montair lc": ["montelukast", "levocetirizine"],
    "montek lc": ["montelukast", "levocetirizine"],
    "janumet": ["sitagliptin", "metformin"],
    "glycomet gp": ["glimepiride", "metformin"],
    "telma h": ["telmisartan", "hydrochlorothiazide"],
    "telma am": ["telmisartan", "amlodipine"],
    "zerodol p": ["aceclofenac", "paracetamol"],
    "ecosprin av": ["aspirin", "atorvastatin"],
    "clopilet a": ["clopidogrel", "aspirin"],
    "deplatt a": ["clopidogrel", "aspirin"],
    "vomilast": ["doxylamine", "pyridoxine", "folic acid"],
    "doxinate": ["doxylamine", "pyridoxine"],
}

# Products that are recognised but have no single defined chemical structure
# (nutritional supplements, biologics). They are shown to the user but are
# not sent to the structure-based interaction model.
NON_CHEMICAL_PRODUCTS = {
    "sm fibro": ("nutritional_supplement", "SM Fibro (nutritional supplement)"),
    "becosules": ("nutritional_supplement", "Becosules (B-complex supplement)"),
    "zincovit": ("nutritional_supplement", "Zincovit (multivitamin supplement)"),
    "limcee": ("nutritional_supplement", "Limcee (vitamin C supplement)"),
    "insulin": ("biologic", "Insulin"),
    "heparin": ("anticoagulant", "Heparin"),
    "enoxaparin": ("anticoagulant", "Enoxaparin"),
    "abciximab": ("antiplatelet", "Abciximab"),
}

# Words that follow a drug name as its salt / release form and must not be
# treated as separate drugs ("Losartan Potassium", "Metformin HCl ER").
SALT_WORDS = [
    "sodium", "potassium", "hydrochloride", "hcl", "besylate", "besilate", "maleate", "succinate",
    "tartrate", "calcium", "magnesium", "mesylate", "citrate", "phosphate", "sulfate", "sulphate",
    "bromide", "acetate", "dihydrate", "monohydrate", "trihydrate", "fumarate", "er", "sr", "xr",
    "cr", "xl", "od", "dsr", "forte",
]
