services:
  - type: web
    name: rxshield-fastapi-backend
    env: python
    region: oregon
    # Tell Render to navigate into the backend folder first
    buildCommand: cd backend && pip install -r requirements.txt
    # Use the uvicorn start command for production
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: AWS_REGION
        value: us-east-1